name: mocklet_source
description: "Near complete source code of Mocklet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  video_player: ^2.10.0
  dio: ^5.9.0
  google_mobile_ads: ^6.0.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.2
  country_flags: ^3.3.0
  logger: ^2.6.1
  email_validator: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  syncfusion_flutter_charts: ^30.2.4
  url_launcher: ^6.3.2
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  google_sign_in: ^7.1.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/video/
    - assets/images/
